export enum COLORS {
    DEFAULT = "default",
    BLACK_PRIMARY = "black-primary",
    BLACK_SECONDARY = "black-secondary",
    BLACK_GHOST = "black-ghost",
    BRAND_PRIMARY = "brand-primary",
    BRAND_SECONDARY = "brand-secondary",
    BRAND_GHOST = "brand-ghost",
    BRAND_HOVER = "brand-hover",
    SUCCESS_PRIMARY = "success-primary",
    SUCCESS_SECONDARY = "success-secondary",
    SUCCESS_GHOST = "success-ghost",
    WARNING_PRIMARY = "warning-primary",
    WARNING_SECONDARY = "warning-secondary",
    WARNING_GHOST = "warning-ghost",
    ERROR_PRIMARY = "error-primary",
    ERROR_GHOST = "error-ghost",
    SPECIAL_WHITE = "special-white",
    SPECIAL_DISABLED_PRIMARY = "special-disabled-primary",
    SPECIAL_DISABLED_SECONDARY = "special-disabled-secondary",
    SPECIAL_DIVIDER = "special-divider",
    SPECIAL_BACKGROUND = "special-background",
    GENERAL_SECONDARY = "general-secondary",
    SOFT_BLUE = "soft-blue",
}
